# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Color.create [{rgbvalue: '000', difficulty_level: 'easy'} ,
	{rgbvalue: 'fff', difficulty_level: 'easy'},
	{rgbvalue: 'f00', difficulty_level: 'easy'},
	{rgbvalue: '00f', difficulty_level: 'easy'},
    {rgbvalue: '0f0', difficulty_level: 'easy'},
    {rgbvalue: '0ff', difficulty_level: 'easy'},
    {rgbvalue: 'ff0', difficulty_level: 'easy'},
    {rgbvalue: 'f0f', difficulty_level: 'easy'},
    {rgbvalue: '007', difficulty_level: 'medium'},
	{rgbvalue: '700', difficulty_level: 'medium'},
	{rgbvalue: '070', difficulty_level: 'medium'},
    {rgbvalue: '770', difficulty_level: 'medium'},
    {rgbvalue: '077', difficulty_level: 'medium'},
    {rgbvalue: '707', difficulty_level: 'medium'},
    {rgbvalue: '777', difficulty_level: 'medium'},
    {rgbvalue: 'ff7', difficulty_level: 'medium'},
	{rgbvalue: '7ff', difficulty_level: 'medium'},
	{rgbvalue: 'f7f', difficulty_level: 'medium'},
    {rgbvalue: '77f', difficulty_level: 'medium'},
    {rgbvalue: 'f77', difficulty_level: 'medium'},
    {rgbvalue: '7f7', difficulty_level: 'medium'},
    {rgbvalue: '0f7', difficulty_level: 'medium'},
    {rgbvalue: 'f07', difficulty_level: 'medium'},
	{rgbvalue: '7f0', difficulty_level: 'medium'},
	{rgbvalue: '70f', difficulty_level: 'medium'},
	{rgbvalue: 'f70', difficulty_level: 'medium'},
	{rgbvalue: '07f', difficulty_level: 'medium'},
    {rgbvalue: '004', difficulty_level: 'hard'},
    {rgbvalue: '400', difficulty_level: 'hard'},
    {rgbvalue: '040', difficulty_level: 'hard'},
    {rgbvalue: '440', difficulty_level: 'hard'},
    {rgbvalue: '044', difficulty_level: 'hard'},
    {rgbvalue: '404', difficulty_level: 'hard'},
    {rgbvalue: '444', difficulty_level: 'hard'},
    {rgbvalue: 'ff4', difficulty_level: 'hard'},
    {rgbvalue: '4ff', difficulty_level: 'hard'},
    {rgbvalue: 'f4f', difficulty_level: 'hard'},
    {rgbvalue: '44f', difficulty_level: 'hard'},
    {rgbvalue: 'f44', difficulty_level: 'hard'},
    {rgbvalue: '4f4', difficulty_level: 'hard'},
    {rgbvalue: '0f4', difficulty_level: 'hard'},
    {rgbvalue: 'f04', difficulty_level: 'hard'},
    {rgbvalue: '4f0', difficulty_level: 'hard'},
    {rgbvalue: '40f', difficulty_level: 'hard'},
    {rgbvalue: 'f40', difficulty_level: 'hard'},
    {rgbvalue: '04f', difficulty_level: 'hard'},
    {rgbvalue: '009', difficulty_level: 'hard'},
    {rgbvalue: '900', difficulty_level: 'hard'},
    {rgbvalue: '090', difficulty_level: 'hard'},
    {rgbvalue: '990', difficulty_level: 'hard'},
    {rgbvalue: '099', difficulty_level: 'hard'},
    {rgbvalue: '909', difficulty_level: 'hard'},
    {rgbvalue: '999', difficulty_level: 'hard'},
    {rgbvalue: 'ff9', difficulty_level: 'hard'},
    {rgbvalue: '9ff', difficulty_level: 'hard'},
    {rgbvalue: 'f9f', difficulty_level: 'hard'},
    {rgbvalue: '99f', difficulty_level: 'hard'},
    {rgbvalue: 'f99', difficulty_level: 'hard'},
    {rgbvalue: '9f9', difficulty_level: 'hard'},
    {rgbvalue: '0f9', difficulty_level: 'hard'},
    {rgbvalue: 'f09', difficulty_level: 'hard'},
    {rgbvalue: '9f0', difficulty_level: 'hard'},
    {rgbvalue: '90f', difficulty_level: 'hard'},
    {rgbvalue: 'f90', difficulty_level: 'hard'},
    {rgbvalue: '09f', difficulty_level: 'hard'},
    {rgbvalue: '049', difficulty_level: 'hard'},
    {rgbvalue: '094', difficulty_level: 'hard'},
    {rgbvalue: '490', difficulty_level: 'hard'},
    {rgbvalue: '940', difficulty_level: 'hard'},
    {rgbvalue: '409', difficulty_level: 'hard'},
    {rgbvalue: '904', difficulty_level: 'hard'},
    {rgbvalue: 'f49', difficulty_level: 'hard'},
    {rgbvalue: 'f94', difficulty_level: 'hard'},
    {rgbvalue: '49f', difficulty_level: 'hard'},
    {rgbvalue: '94f', difficulty_level: 'hard'},
    {rgbvalue: '4f9', difficulty_level: 'hard'},
    {rgbvalue: '9f4', difficulty_level: 'hard'},
    {rgbvalue: '449', difficulty_level: 'hard'},
    {rgbvalue: '494', difficulty_level: 'hard'},
    {rgbvalue: '944', difficulty_level: 'hard'},
    {rgbvalue: '994', difficulty_level: 'hard'},
    {rgbvalue: '949', difficulty_level: 'hard'},
    {rgbvalue: '499', difficulty_level: 'hard'}

  ]


